name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release-bins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - uses: actions/setup-go@v6.0.0
        with:
          go-version: 1.24
      - run: go install github.com/golang/mock/mockgen@v1.6.0
      - uses: actions/setup-node@v6.0.0
      - name: Build Web Page
        run: make build-web
      - name: Build go binaries
        run: make release
      - uses: softprops/action-gh-release@v2.4.1
        with:
          files: 'bin/*'
          prerelease: ${{ contains(env.GIT_TAG, 'rc') }}
